# We need thses flags since rust 1.93
# ref: https://github.com/wasm-bindgen/wasm-bindgen/pull/4717
# ref: https://github.com/rust-lang/rust/pull/147225
[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics",
    "-C", "link-arg=--shared-memory",
    "-C", "link-arg=--max-memory=1073741824",
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--export=__wasm_init_tls",
    "-C", "link-arg=--export=__tls_size",
    "-C", "link-arg=--export=__tls_align",
    "-C", "link-arg=--export=__tls_base",
]
